apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: "rishabhdevopspareta/my-node-app:latest"  # Replace with your Docker Hub image
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 
  name: Nodesvs
  labels:
    app: mysql
spec:
  ports:
  - name: node
    port: 3000
    targetport: 3000
 
  selector:
  type: NodePort
  app: my-node-app

        
